config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pictures#index"
  
  resources :pictures, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create]
  end

  resources :users, only: [:edit, :update, :new, :create, :show, :index]

  # Agregamos la ruta para eliminar un comentario si también lo deseas
  resources :comments, only: [:index, :new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :content, presence: true
end

app/models/picture.rb
# app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  has_one_attached :image

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :profile_picture
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def index
      @comments = Comment.all # Aquí obtienes todos los comentarios de la base de datos
    end

    def new
      @comment = Comment.new
    end

    def create
      @picture = Picture.find(params[:picture_id])
      @comment = @picture.comments.build(comment_params)
      @comment.user = current_user
  
      if @comment.save
        redirect_to @picture, notice: "Comentario agregado con éxito."
      else
        redirect_to @picture, alert: "Error al agregar el comentario."
      end
    end
  
    private
  
    def comment_params
      params.require(:comment).permit(:content)
    end
  end
  

app/controllers/pictures_controller.rb
# app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
  
    def index
      @pictures = Picture.all
    end
    
    def edit
        @picture = Picture.find(params[:id])
      end

    def show
      @picture = Picture.find(params[:id])
    end
  
    def new
      @picture = Picture.new
    end
  
    def create
      @picture = Picture.new(picture_params)
      @picture.user = current_user
  
      if @picture.save
        @picture.image.attach(params[:picture][:image]) if params[:picture][:image].present?
        redirect_to @picture, notice: "Imagen subida con éxito."
      else
        render :new
      end
    end
  
    private
  
    def picture_params
      params.require(:picture).permit(:name, :description, :image)
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create]

  def new
    @user = User.new
  end

  def index
    @users = User.includes(:profile_picture_attachment).all
  end

  def create
    @user = User.new(user_params)
    @user.profile_picture.attach(params[:user][:profile_picture])
    if @user.save
      redirect_to root_path, notice: "Usuario registrado exitosamente."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_user_registration_path, notice: "Perfil actualizado exitosamente."
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :profile_picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div>
  <p>
    <strong>User:</strong>
    <%= comment.user.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Commentable Type:</strong>
    <%= comment.commentable_type %>
  </p>

  <p>
    <strong>Commentable ID:</strong>
    <%= comment.commentable_id %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :picture_id, style: "display: block" %>
    <%= form.text_field :picture_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>All Comments</h1>

<% @comments.each do |comment| %>
  <% if comment.user %>
    <p><strong><%= comment.user.name %>:</strong> <%= comment.content %></p>
  <% else %>
    <p><strong>Usuario Desconocido:</strong> <%= comment.content %></p>
  <% end %>
<% end %>



<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KarinaPhotographerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Galeria", pictures_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
        <%= link_to "Registro", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Comentarios", comments_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Usuarios", users_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture) do |form| %>
  <% if picture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div id="<%= dom_id picture %>">
  <p>
    <strong>Name:</strong>
    <%= picture.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= picture.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= picture.user_id %>
  </p>

</div>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Show this picture", @picture %> |
  <%= link_to "Back to pictures", pictures_path %>
</div>

app/views/pictures/index.html.erb
<!-- app/views/pictures/index.html.erb -->
<div class="container text-center">
  <div class="row">
    <% @pictures.each do |picture| %>
      <div class="col">
        <div class="card" style="width: 18rem;">
          <% if picture.image.attached? %>
            <%= link_to image_tag(picture.image, class: "card-img-top"), picture %>
          <% else %>
            <%= image_tag "placeholder_image.png", class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= picture.name %></h5> 
            <p class="card-text"><%= picture.description %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Back to pictures", pictures_path %>
</div>

app/views/pictures/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @picture %>
<h1><%= @picture.name %></h1>
<p><%= @picture.description %></p>

<%= form_for([@picture, Comment.new]) do |form| %>
  <%= form.text_area :content, placeholder: "Escribe un comentario..." %>
  <%= form.submit "Comentar" %>
<% end %>

<h2>Comentarios:</h2>
<% @picture.comments.each do |comment| %>
  <p><%= comment.content %></p>
<% end %>

<div>
  <%= link_to "Edit this picture", edit_picture_path(@picture) %> |
  <%= link_to "Back to pictures", pictures_path %> |
  <%= link_to "All Comments", comments_path %>
  <%= button_to "Destroy this picture", @picture, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, url: users_path) do |form| %> <!-- Agrega `url: users_path` para que apunte a la ruta de creación de usuarios -->
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.label :profile_picture %>
    <%= form.file_field :profile_picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Profile picture:</strong>
    <%= user.profile_picture_id %>
  </p>

</div>

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->
<h2>Edit User Profile</h2>

<%= form_for(current_user, url: user_path, html: { method: :put, multipart: true }) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :current_password %>
  <%= form.password_field :current_password %>

  <%= form.label :profile_picture %>
  <%= form.file_field :profile_picture %>

  <%= form.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<% @users.each do |user| %>
  <div>
    <% if user.profile_picture.attached? %>
      <%= image_tag url_for(user.profile_picture), class: "profile-picture" %>
    <% else %>
      <%= image_tag "default_profile_picture.png", class: "profile-picture" %>
    <% end %>
    <h3><%= user.name %></h3>
    <!-- Otros detalles del usuario que quieras mostrar en el índice -->
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>